---
version: '3.8'

services:
  app:
    image: numa:latest
  nginx-sidecar:
    image: numa-nginx-sidecar:latest
    ports:
      - 80:80
    environment:
      - NGINX_LISTEN_PORT=80
      - NGINX_PROXY_HOST=app
      - NGINX_PROXY_PORT=8080
      - NGINX_REWRITE=^/numa/(.*)
